services:
  app:
    image: php:8.5-apache
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - app_data:/var/www/html
    networks:
      - appnet 
  db:
    image: mysql:9.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet 
      - dbadminnet
  dbadmin:
    image: phpmyadmin:5.2
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
    networks:
      - dbadminnet
volumes:
  db_data:
  app_data:
    driver: local
    driver_opts:
      type: none
      device: ./app
      o: bind
networks:
  appnet:
  dbadminnet:
